name: generate_example
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  go_router: ^6.5.5
  riverpod: ^2.3.6
  state_notifier: ^0.7.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
