name: generate_hooks

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mason: ^0.1.0-dev
  path: ^1.8.3
  yaml: ^3.1.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0
